name: torch
channels:
  - stellargraph
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h5764c6d_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.5=pyhd8ed1ab_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2023.5.7=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py310h06a4308_0
  - cryptography=38.0.1=py310h9ce1e76_0
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.6.2=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-visual-tools=11.6.2=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310h06a4308_0
  - expat=2.2.10=h9c3ff4c_0
  - flatbuffers=2.0.0=h2531618_0
  - fontconfig=2.13.1=hef1e5e3_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.2.0=py310h7f8727e_1
  - fsspec=2022.11.0=pyhd8ed1ab_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gds-tools=1.4.0.31=0
  - gensim=4.3.0=py310h1128e8f_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.69.1=h4ff587b_1
  - google-auth=2.14.1=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.46.1=h33aed49_0
  - grpcio=1.42.0=py310hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.7.0=py310he06866b_0
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=5.0.0=pyha770c72_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py310h2f386ee_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jupyter_client=7.3.4=py310h06a4308_0
  - jupyter_core=5.3.0=py310h06a4308_0
  - keras=2.10.0=py310h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py310h295c915_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h9c3ff4c_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcurl=7.87.0=h91b91d3_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.4.0=hecacb30_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib=3.5.3=py310hff52083_2
  - matplotlib-base=3.5.3=py310hf590b9c_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - multidict=6.0.2=py310h5764c6d_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nltk=3.7=pyhd8ed1ab_0
  - nsight-compute=2022.3.0.22=0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.24.3=py310hd5efca6_0
  - numpy-base=1.24.3=py310h8e6c178_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1u=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py310hace64e9_1
  - pip=22.2.2=py310h06a4308_0
  - platformdirs=2.5.2=py310h06a4308_0
  - ply=3.11=py_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - portalocker=2.3.0=py310h06a4308_0
  - protobuf=3.20.1=py310h295c915_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pygments=2.15.1=py310h06a4308_1
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.8=haa1d7c7_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.0=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-lightning=1.7.7=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=25.1.0=py310h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py310h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py310h6a678d5_1
  - scipy=1.10.1=py310hd5efca6_0
  - setuptools=65.5.0=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=5.2.1=py310h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.40.0=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stellargraph=1.2.1=py_0
  - tensorboard=2.10.0=py310h06a4308_0
  - tensorboard-data-server=0.6.0=py310h597c629_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=mkl_py310h24f4fea_0
  - tensorflow-base=2.10.0=mkl_py310hb9daa73_0
  - tensorflow-estimator=2.10.0=py310h06a4308_0
  - termcolor=2.1.0=py310h06a4308_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchdata=0.5.0=py310
  - torchmetrics=0.10.3=pyhd8ed1ab_0
  - tornado=6.1=py310h5764c6d_3
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typing-extensions=4.3.0=py310h06a4308_0
  - typing_extensions=4.3.0=py310h06a4308_0
  - tzdata=2022f=h04d1e81_0
  - urllib3=1.26.12=py310h06a4308_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - adjusttext==0.8
      - alembic==1.11.1
      - asttokens==2.2.1
      - catboost==1.2
      - chardet==5.1.0
      - cloudpickle==2.2.1
      - cmaes==0.9.1
      - colorlog==6.7.0
      - cython==0.29.36
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - filelock==3.12.2
      - fst-pso==1.8.1
      - fuzzytm==2.0.5
      - gradient-descent-the-ultimate-optimizer==1.0
      - greenlet==2.0.2
      - hdbscan==0.8.30
      - huggingface-hub==0.16.3
      - imbalanced-learn==0.11.0
      - imblearn==0.0
      - ipdb==0.13.13
      - ipython==8.14.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - kaleido==0.2.1
      - llvmlite==0.40.1
      - mako==1.2.4
      - miniful==0.0.6
      - networkx==3.1
      - numba==0.57.1
      - openai==0.27.8
      - openpyxl==3.1.2
      - opentsne==1.0.0
      - optuna==3.2.0
      - pandas==1.5.2
      - plotly==5.14.1
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - pyfume==0.2.25
      - pyqt5-sip==12.11.0
      - python-graphviz==0.20.1
      - pytz==2022.6
      - safetensors==0.3.1
      - shap==0.42.1
      - simpful==2.11.0
      - slicer==0.0.7
      - sqlalchemy==2.0.18
      - stack-data==0.6.2
      - tenacity==8.2.2
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch-geometric==2.3.1
      - torch-tb-profiler==0.4.0
      - traitlets==5.9.0
      - transformers==4.30.2
      - wcwidth==0.2.6
      - xmltodict==0.13.0
prefix: /home/borneta/miniconda3/envs/torch
